### PR TITLE
backup: dump stats to json should not be fatal (#682)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #682 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In br repo:
git pr 686
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/br.git pr/686:ti-srebot:release-4.0-5abd5baa56e6
```

---

also improved some logs

### What problem does this PR solve? 

Part 1 of #679. 

### What is changed and how it works?

If the stats is broken, we just log and skip it instead of bailing out.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - Failing to backup statistics is no longer fatal.

### CODE REVIEW

**Review by 3pointer — COMMENTED** [review]
LGTM

**Comment by kennytm** [comment]
/run-all-tests

🤔 https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/4558/pipeline

```
[2021-01-11T07:40:47.288Z] + rm -rf /tmp/backup_restore_test
[2021-01-11T07:40:47.288Z] rm: cannot remove '/tmp/backup_restore_test': Directory not empty
```

**Comment by overvenus** [comment]
LGTM

**Comment by kennytm** [comment]
(Hound is broken)

**Review by kennytm — APPROVED** [review]

**Pull request merged**
