### PR TITLE
*: report error if service safe point check fails (#825)

### LINKED ISSUE #823: BR should report error not panic if gc safepoint ts excess backup ts before running backup/restore task
1. What did you do?
If possible, provide a recipe for reproducing the error.

Backup with a ts that is less than gc safepoint. 

2. What did you expect to see?

BR reports error instead of running the backup task.

3. What did you see instead?

BR panics.

```
panic: cannot pass gc safe point check, aborting

goroutine 224 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000adbd40, 0xc000d0f780, 0x2, 0x2)
go.uber.org/zap@v1.16.0/zapcore/entry.go:234 +0x567
go.uber.org/zap.(*Logger).Panic(0xc0016fb6e0, 0x23a4105, 0x29, 0xc000d0f780, 0x2, 0x2)
go.uber.org/zap@v1.16.0/logger.go:226 +0x7f
github.com/pingcap/log.Panic(0x23a4105, 0x29, 0xc000d0f780, 0x2, 0x2)
github.com/pingcap/log@v0.0.0-20201112100606-8f1e84a3abc8/global.go:50 +0xff
github.com/pingcap/br/pkg/utils.StartServiceSafePointKeeper.func2(0x288e4a0, 0xc000226440)
github.com/pingcap/br@/pkg/utils/safe_point.go:111 +0x358
github.com/pingcap/br/pkg/utils.StartServiceSafePointKeeper.func3(0xc000c204b0, 0xc000c20500, 0x288e4a0, 0xc000226440, 0xc00002b380, 0xc00002b680)
github.com/pingcap/br@/pkg/utils/safe_point.go:131 +0x1b5
created by github.com/pingcap/br/pkg/utils.StartServiceSafePointKeeper
github.com/pingcap/br@/pkg/utils/safe_point.go:120 +0x209
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #825 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In br repo:
git pr https://github.com/pingcap/br/pull/826
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/br.git pr/826:release-4.0-1a5c9e5dc3ad
```

---

### What problem does this PR solve? 

Close #823

Report error if service safe point check fails

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - Report error if service safe point check fails

### CODE REVIEW

**Comment by YuJuncen** [comment]
`checksum mismatched remote vs local => (checksum: 789803659099732364 vs 3203001050118138354) (total_kvs: 2 vs 4)` (#765)

/run-integration-test

**Review by overvenus — APPROVED** [review]

**Pull request merged**
