### PR TITLE
tidb_tools: update dependency

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve? 
update filter dependency to solve https://github.com/pingcap/tidb-tools/pull/382

### What is changed and how it works?
update go mod

### Check List 

Tests 

 - No code

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - No release note

### CODE REVIEW

**Comment by YuJuncen** [comment]
LGTM

**Comment by kennytm** [comment]
LGTM

**Comment by kennytm** [comment]
/run-all-tests

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/2643/pipeline

> Failed to start minio

**Pull request merged**
