### PR TITLE
gcs: compatible with old gcs bug (#677)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #677 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In br repo:
git pr 688
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/br.git pr/688:ti-srebot:release-4.0-3de76b2ec3f2
```

---

### What problem does this PR solve? 
solve #675

### What is changed and how it works?
for case 1: add a check before Read & Write meta file, decide which prefix to use.
for case 2: check whether sst file is in Prefix(after #647) or in PrefixSlash(before #647), adjust proper prefix for TiKV request.
### Check List 

Tests 
 - Integration test

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Release Note

 - Fix the issue that br 4.0.9 cannot restore br 4.0.8 gcs backup files.

### CODE REVIEW

**Comment by 3pointer** [comment]
`
[2021-01-11T11:30:05.513Z] [2021/01/11 19:29:49.775 +08:00] [FATAL] [server.rs:846] ["0.0.0.0_20170 already in use, maybe another instance is binding with this address."]`

**Comment by overvenus** [comment]
LGTM

**Comment by kennytm** [comment]
Lgtm

**Review by kennytm — APPROVED** [review]

**Pull request merged**
