### PR TITLE
lightning: emit scan region log

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Only output scan region log in `SplitAndScatterRegionByRanges` but not every call in `local.writeAndIngestByRange`

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Release note

 - No release note

### CODE REVIEW

**Review by overvenus — COMMENTED** [review]
Could you unify BR and Lightning PaginateScanRegion?

**Review by 3pointer — APPROVED** [review]

**Review by kennytm — APPROVED** [review]

**Pull request merged**
