### PR TITLE
test: fix unstable test checkpoint-parquet

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Add `primary key` to the test table schema to avoid tidb backend insert more rows when restart from checkpoint.

See： https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/5281/pipeline/

### Check List 

Tests 

 - Integration test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Release note

 - No release note

### CODE REVIEW

**Review by gozssky — APPROVED** [review]

**Review by kennytm — APPROVED** [review]
sounds like a bug of TiDB backend though 😅

**Comment by glorv** [comment]
> sounds like a bug of TiDB backend though 😅

The only way to solve this issue for table without pk/uk is to explicitly set `_tidb_rowid` 😂

**Review by gozssky — APPROVED** [review]

**Pull request merged**
