### PR TITLE
Fix speed compute

### PR DESCRIPTION
**Pull request by joccau**
### What problem does this PR solve? 
fix issue: the average speed isn't accurate(https://github.com/pingcap/br/issues/1405)

### What is changed and how it works?
change the  Calculation method for speed

### Check List
Tests 
 - Manual test (add detailed scripts or steps below)
 
**command**
  ./br backup full --pd "172.16.6.117:2379" --compression-level 3 --storage "local:///home/zak/new_br"
  ./br restore full --pd "172.16.6.117:2379" --storage "local:///home/zak/new_br"
**log**
[2021/08/04 10:03:34.913 +08:00] [INFO] [collector.go:67] ["Full backup success summary"] [total-ranges=45] [ranges-succeed=45] [ranges-failed=0] [backup-checksum=3.515718214s] [backup-fast-checksum=7.003603ms] [backup-total-ranges=58] [backup-total-regions=77] [total-take=14.017946255s] [total-kv=15463846] [total-kv-size=1.859GB] [average-speed=132.6MB/s] ["backup data size(after compressed)"=496.8MB] [BackupTS=426781599562989570]

[2021/08/04 10:06:45.055 +08:00] [INFO] [collector.go:67] ["Full restore success summary"] [total-ranges=37] [ranges-succeed=37] [ranges-failed=0] [split-region=362.373805ms] [restore-checksum=6.890396086s] [restore-ranges=29] [total-take=17.328491842s] ["restore data size(after compressed)"=496.7MB] [total-kv=15462460] [total-kv-size=1.858GB] [average-speed=107.2MB/s]

### Release note
- fix the bug that the average speed isn't accurate in `backup` and `restore`

### CODE REVIEW

**Review by lichunzhu — APPROVED** [review]
LGTM

**Comment by joccau** [comment]
> [REVIEW NOTIFICATION]
> 
> This pull request has been approved by:
> 
> * lichunzhu
> 
> To complete the [pull request process](https://book.prow.tidb.io/#/en/workflows/pr), please ask the reviewers in the [list](https://prow.tidb.io/tichi/repos/pingcap/br/pulls/1408/owners) to review by filling `/cc @reviewer` in the comment.
> After your PR has acquired the required number of LGTMs, you can assign this pull request to the committer in the [list](https://prow.tidb.io/tichi/repos/pingcap/br/pulls/1408/owners) by filling `/assign @committer` in the comment to help you merge this pull request.
> 
> The full list of commands accepted by this bot can be found [here](https://prow.tidb.io/command-help?repo=pingcap%2Fbr).
> 
> Reviewer can indicate their review by submitting an approval review.
> Reviewer can cancel approval by submitting a request changes review.

**Review by YuJuncen — APPROVED** [review]

**Pull request merged**
