### PR TITLE
lightning: fix duplicated engine counter metrics (#777)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #777 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In br repo:
git pr https://github.com/pingcap/br/pull/946
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/br.git pr/946:release-5.0-fa66494bcf93
```

---

### What problem does this PR solve? 
Fix duplicated engine counter like following:
```
[2021/03/02 18:10:06.078 +08:00] [INFO] [restore.go:961] [progress] [total=100.0%] [tables="1/1 (100.0%)"] [chunks="100/100 (100.0%)"] [engines="6/3 (200.0%)"] [speed(MiB/s)=35.39753062725018] [state=post-processing]
```

### What is changed and how it works?
- Fix lightning engine finished counter
- Move the `RestoreController.postProcessLock` into import because it only affects importEngine for import backend

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - No release note

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by lysu** [comment]
need merge https://github.com/pingcap/br/pull/944 first to pass 5.0 integration test

**Comment by kennytm** [comment]
```
[2021-03-27T06:42:22.495Z] Error: restore table `cpeng`.`b` failed: rpc error: code = Unknown desc = FileExists("/tmp/backup_restore_test/importer/59efc1a8-2641-59cf-8636-f6c3df916276")

[2021-03-27T06:42:22.495Z] tidb lightning encountered error:  restore table `cpeng`.`b` failed: rpc error: code = Unknown desc = FileExists("/tmp/backup_restore_test/importer/59efc1a8-2641-59cf-8636-f6c3df916276")
```

/merge

**Pull request merged**
