### PR TITLE
[cherry-pick] restore: fix failed to retry grpc errors(tidb#27423)

### PR DESCRIPTION
**Pull request by YuJuncen**
cherry-picking tidb#27423

=== 

### What problem does this PR solve?

Issue Number: close #27421 

Problem Summary:
BR used the wrapped error to get the gRPC error code, which would always returning a Unknown code.

### What is changed and how it works?

What's Changed:
Use the unwrapped error.

How it Works:
So the code would be right.

### Check List 

Tests 

- [ ] Integration test

### Release note 

```release-note
Increase the robustness for restoring. 
```

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Review by glorv — APPROVED** [review]

**Comment by YuJuncen** [comment]
Reopen for triggering CLA？

**Pull request merged**
