### PR TITLE
Update PD and adapt new PD client APIs

### PR DESCRIPTION
**Pull request by sticnarf**
### What is changed and how it works?

New PD client changes the API of `ScanRegions`. TiDB and BR won't compile with new PD.

To make TiDB compile, TiDB is now using a non-master branch of br (https://github.com/pingcap/br/tree/update-pd-20200803). In that branch, some changes are done to adapt new PD client APIs. This PR intends to merge it to master.

### Check List 

Tests 

 - No code

### Release Note

No release note.

### CODE REVIEW

**Comment by overvenus** [comment]
LGTM

**Comment by sticnarf** [comment]
@3pointer Need we cherry pick it to 4.0？The corresponding PD change is not cherry picked to 4.0 https://github.com/pingcap/pd/pull/2649

**Pull request merged**
