### PR TITLE
restore: Fix typo of system db in release-4.0

### PR DESCRIPTION
**Pull request by zwj-coder**
### What problem does this PR solve? 
```
if !f.MatchSchema(temporaryDB.O) {
```
The system db name specified is not matched with the `temporaryDB.O`, which will cause system db be filtered out

### What is changed and how it works?

Change `temporaryDB.O` to `sysDB`

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

 - No Release Note

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]

**Comment by kennytm** [comment]
https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/br_ghpr_unit_and_integration_test/runs/5007/nodes/87/steps/1002/log/?start=0

```
[2021-06-18T09:57:18.209Z] fatal error: concurrent map read and map write
[2021-06-18T09:57:18.209Z] 
[2021-06-18T09:57:18.209Z] goroutine 14889 [running]:
[2021-06-18T09:57:18.209Z] runtime.throw(0x247137b, 0x21)
[2021-06-18T09:57:18.209Z] 	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00351cd90 sp=0xc00351cd60 pc=0xc815c2
[2021-06-18T09:57:18.209Z] runtime.mapaccess2_fast64(0x2190620, 0xc0001dbda0, 0x4, 0xc0001dbda0, 0x1cc6f01)
[2021-06-18T09:57:18.209Z] 	/usr/local/go/src/runtime/map_fast64.go:61 +0x1b5 fp=0xc00351cdb8 sp=0xc00351cd90 pc=0xc63835
[2021-06-18T09:57:18.209Z] github.com/tikv/pd/server/schedule.(*selectedStores).totalCountByStore(0xc0018ab8a0, 0x4, 0x0)
```

looks like tikv/pd#3760

**Pull request merged**
