### PR TITLE
[cherry-pick] backup: more detailed TiKV error message(tidb#27567)

### PR DESCRIPTION
**Pull request by YuJuncen**
cherry-picking tidb#27567

=== 

### What problem does this PR solve?

Problem Summary:

The error information when meeting unknown TiKV storage error is too abstract...

### What is changed and how it works?

What's Changed:
Added more details to the error.

How it Works:
So we can get more detailed information.

### Check List 

Tests 

- [ ] (almost) No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by zwj-coder** [comment]
why unit test failed.

**Comment by YuJuncen** [comment]
```
[2021-09-23T06:33:08.489Z] FAIL: configlist_test.go:59: configListTestSuite.TestContextCancel
[2021-09-23T06:33:08.489Z] 
[2021-09-23T06:33:08.489Z] configlist_test.go:70:
[2021-09-23T06:33:08.489Z]     c.Assert(time.Since(startTime), GreaterEqual, 400*time.Millisecond)
[2021-09-23T06:33:08.489Z] ... compare_one time.Duration = 398425490 ("398.42549ms")
[2021-09-23T06:33:08.489Z] ... compare_two time.Duration = 400000000 ("400ms")
[2021-09-23T06:33:08.489Z] 
```
🤔

**Review by kennytm — APPROVED** [review]

**Review by zwj-coder — APPROVED** [review]

**Pull request merged**
