### PR TITLE
brieSQL: fix multi-thread panic during SQL restore

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve? 
In SQL restore. we choose one session to execute SQL, 
so we can't simple use dbPool to create table concurrently.

### What is changed and how it works?
In restore. if we are using SQL `glue.OwnerStorage()` will return false. 
so we use this condition to tell whether we should make dbPool or not.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
test will include in https://github.com/pingcap/tidb/pull/18993

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Release Note

 - No release note

### CODE REVIEW

**Comment by overvenus** [comment]
LGTM

**Comment by 3pointer** [comment]
[2020-08-05T06:36:37.592Z] Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = System exception: cannot start thread: Resource temporarily unavailable, e.what() = System exception

**Pull request merged**
