### PR TITLE
restore: remove table field from rewrite rules

### PR DESCRIPTION
**Pull request by zwj-coder**
### What problem does this PR solve? 
struct RewriteRules now has two field
```go
type RewriteRules struct {
	Table []*import_sstb.RewriteRule
	Data  []*import_sstpb.RewriteRule
}
```
field `Table` is unnecessary, this pull request remove that field and provide compatible test.

### What is changed and how it works?
This modified `RewriteRules` struct in `pkg/restore/range.go` file and changed all code related with `Table` field

### Check List 

Tests 
 - Manual test (add detailed scripts or steps below)
 Using tiup bench to generate 100 warehourse tpcc data, and run modified BR on various tikv version including v4.0.9, v4.0.12, v5.0.0

**TiKV 4.0.9 + BR fix-rewrite-rules version**
```
[collector.go:62] ["Database restore success summary"] [total-ranges=253] [ranges-succeed=253] [ranges-failed=0] [split-region=55.671636681s] [restore-checksum=2m3.436042676s] [restore-ranges=179] [Size=4806591284] [total-take=1m47.475833605s] [total-kv=108904178] [data-size=12.37GB] [average-speed=68.15MB/s]
```
**TiKV 4.0.12 + BR fix-rewrite-rules version**
```
[collector.go:62] ["Database restore success summary"] [total-ranges=253] [ranges-succeed=253] [ranges-failed=0] [split-region=52.530581048s] [restore-checksum=2m56.746218609s] [restore-ranges=179] [Size=4806591284] [total-take=2m5.797748427s] [total-kv=108904178] [data-size=12.37GB] [average-speed=53.95MB/s]
```
**TiKV 5.0.0 + BR fix-rewrite-rules version**
```
[collector.go:62] ["Database restore success summary"] [total-ranges=253] [ranges-succeed=253] [ranges-failed=0] [split-region=42.622399681s] [restore-checksum=2m10.806211667s] [restore-ranges=179] [Size=4806591638] [total-take=1m56.536507342s] [total-kv=108904178] [data-size=12.37GB] [average-speed=69.18MB/s]
```
Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has persistent data change

### Release Note

 - No Release Note

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Comment by zwj-coder** [comment]
TEST: [br_full_ddl] fail due to stats are not equal

**Comment by kennytm** [comment]
maybe try update the branch to latest master first

**Pull request closed without merging**
