### PR TITLE
cdclog: Fix bugs and add tests for cdclog feature (#573)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #573 to release-4.0

---

### What problem does this PR solve? 
Fix the bug that create and drop and create table/database.

### What is changed and how it works?
Add tests for https://github.com/pingcap/br/pull/568

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - No release note

### CODE REVIEW

**Review by kennytm — COMMENTED** [review]
lgtm, but please fix the CI failure.

```
[2020-11-09T10:03:07.152Z] level=warning msg="[runner] Can't run linter goanalysis_metalinter: rowserrcheck: failed prerequisites: [buildssa@github.com/pingcap/br/pkg/restore_test [github.com/pingcap/br/pkg/restore.test]: analysis skipped: errors in package: [/home/jenkins/agent/workspace/br_ghpr_build/go/src/github.com/pingcap/br/pkg/restore/log_client_test.go:31:57: undeclared name: defaultKeepaliveCfg]]"
```

**Comment by 3pointer** [comment]
> lgtm, but please fix the CI failure.
> 
> ```
> [2020-11-09T10:03:07.152Z] level=warning msg="[runner] Can't run linter goanalysis_metalinter: rowserrcheck: failed prerequisites: [buildssa@github.com/pingcap/br/pkg/restore_test [github.com/pingcap/br/pkg/restore.test]: analysis skipped: errors in package: [/home/jenkins/agent/workspace/br_ghpr_build/go/src/github.com/pingcap/br/pkg/restore/log_client_test.go:31:57: undeclared name: defaultKeepaliveCfg]]"
> ```

let's merge https://github.com/pingcap/br/pull/591 first

**Comment by kennytm** [comment]
#591 Already merged.

**Review by overvenus — APPROVED** [review]
LGTM

**Pull request merged**
