### PR TITLE
cherry-pick #247 to 3.1

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve? 

cherry-pick #247 to 3.1 manually.

### Release Note

 - fix the problem that might cause: when restoring many small tables, br failed on error `NotLeader`.

### CODE REVIEW

**Comment by YuJuncen** [comment]
Meet many `[ERROR] [client.go:259] ["[pd] getTS error"] [error="rpc error: code = Unknown desc = alloc timestamp failed, lease expired"]`... Maybe wrong version of client used?

**Comment by kennytm** [comment]
PTAL @overvenus

**Pull request merged**
