### PR TITLE
pkg/mock, pkg/lightning: unify mock files (#786)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #786 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In br repo:
git pr https://github.com/pingcap/br/pull/788
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/br.git pr/788:release-4.0-f1daf8a4d6d1
```

---

### What problem does this PR solve? 

Unify mock files of BR and Lightning.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - No release note.

### CODE REVIEW

**Comment by overvenus** [comment]
Test build fails @kennytm 

```
[2021-03-10T18:14:09.282Z] pkg/lightning/restore/restore_test.go:724:17: undefined: "github.com/pingcap/br/pkg/mock".NewMockBackend
[2021-03-10T18:14:09.282Z] pkg/lightning/restore/restore_test.go:756:17: undefined: "github.com/pingcap/br/pkg/mock".NewMockBackend
[2021-03-10T18:14:09.282Z] pkg/lightning/restore/restore_test.go:832:17: undefined: "github.com/pingcap/br/pkg/mock".NewMockBackend
[2021-03-10T18:14:09.282Z] pkg/lightning/restore/restore_test.go:837:16: undefined: "github.com/pingcap/br/pkg/mock".NewMockEngineWriter
[2021-03-10T18:14:09.282Z] pkg/lightning/restore/restore_test.go:872:17: undefined: "github.com/pingcap/br/pkg/mock".NewMockBackend
[2021-03-10T18:14:09.282Z] pkg/lightning/restore/restore_test.go:877:16: undefined: "github.com/pingcap/br/pkg/mock".NewMockEngineWriter
[2021-03-10T18:14:09.282Z] pkg/lightning/restore/restore_test.go:1087:16: undefined: "github.com/pingcap/br/pkg/mock".NewMockImportKVClient
[2021-03-10T18:14:09.282Z] pkg/lightning/restore/restore_test.go:1088:20: undefined: "github.com/pingcap/br/pkg/mock".NewMockImportKV_WriteEngineClient
[2021-03-10T18:14:09.282Z] pkg/lightning/restore/restore_test.go:1089:21: undefined: "github.com/pingcap/br/pkg/mock".NewMockImportKV_WriteEngineClient
[2021-03-10T18:14:09.282Z] pkg/lightning/restore/restore_test.go:1192:17: undefined: "github.com/pingcap/br/pkg/mock".NewMockBackend
```

**Comment by kennytm** [comment]
let's hold this off until the tikv-client people actually confirmed the working solution.

**Comment by kennytm** [comment]
(the #838 cherry-pick has been reverted.)

**Pull request merged**
