### PR TITLE
summary/: export new log collector

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve? 
dumpling wants to use collector. But the logger is different.

### What is changed and how it works?
export log exporter for dumpling to specify its own logger.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - No release note

### CODE REVIEW

**Review by kennytm — COMMENTED** [review]
please fix lint. rest lgtm.

```
[2020-11-17T11:59:19.487Z] pkg/summary/collector.go:85:1: Top level comment should end in a period (godot)

[2020-11-17T11:59:19.488Z] // NewLogCollector returns a new LogCollector

[2020-11-17T11:59:19.488Z] ^
```

**Review by 3pointer — APPROVED** [review]
LGTM

**Pull request merged**
