### PR TITLE
restore: change batch size (#576)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #576 to release-4.0

---

### What problem does this PR solve? 
1. change restore batch size from 256 to 10240.
2. skip unecessary file download

### Check List 

Tests 
 - Manual test (add detailed scripts or steps below)

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Release Note

 - No release note.

### CODE REVIEW

**Review by lichunzhu — APPROVED** [review]
LGTM

**Comment by overvenus** [comment]
LGTM

**Comment by 3pointer** [comment]
```
[WARN] [split_observer.rs:86] ["invalid key, skip"] [err="\"key 7480000000000000FF345F72FFFFFFFFFFFFFFFFFF0000000000FA should be in (7480000000000000FF345F72FFFFFFFFFFFFFFFFFF0000000000FA, )\""] [index=0] [region_id=2]

[ERROR] [split_observer.rs:149] ["failed to handle split req"] [err="\"no valid key found for split.\""] [region_id=2]
```

**Comment by 3pointer** [comment]
> 7480000000000000FF345F72FFFFFFFFFFFFFFFFFF0000000000FA

it seems 4.0 tikv still have truncateRow [logic](https://github.com/tikv/tikv/blob/release-4.0/components/raftstore/src/coprocessor/split_observer.rs#L32-L42)

**Review by lichunzhu — APPROVED** [review]
LGTM

**Pull request merged**
