### PR TITLE
*: update tidb

### PR DESCRIPTION
**Pull request by sticnarf**
### What problem does this PR solve? 

Lock resolving in TiDB has a bug: https://github.com/pingcap/tidb/issues/24384.

### What is changed and how it works?

Update TiDB to the latest version with the bug fixed.

### Check List 

Tests 

 - No code
 
Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - No release note

### CODE REVIEW

**Comment by kennytm** [comment]
Please update the `(*mockChecksumKVClient) Send` function in `pkg/lightning/restore/checksum_test.go`.

```
[2021-04-30T09:15:40.673Z] pkg/lightning/restore/checksum_test.go:178:76: cannot use kvClient (type *mockChecksumKVClient) as type "github.com/pingcap/tidb/kv".Client in field value:

[2021-04-30T09:15:40.673Z] 	*mockChecksumKVClient does not implement "github.com/pingcap/tidb/kv".Client (wrong type for Send method)

[2021-04-30T09:15:40.673Z] 		have Send(context.Context, *"github.com/pingcap/tidb/kv".Request, *"github.com/pingcap/tidb/store/tikv/kv".Variables, *memory.Tracker, bool) "github.com/pingcap/tidb/kv".Response

[2021-04-30T09:15:40.673Z] 		want Send(context.Context, *"github.com/pingcap/tidb/kv".Request, interface {}, *memory.Tracker, bool) "github.com/pingcap/tidb/kv".Response

```

**Comment by sticnarf** [comment]
@kennytm @overvenus PTAL, thanks!

**Comment by sticnarf** [comment]
Superseded by #1103

**Pull request closed without merging**
