### PR TITLE
Update the errors/parser dependence to the latest version

### PR DESCRIPTION
**Pull request by lonng**
Signed-off-by: Lonng <heng@lonng.org>

### What problem does this PR solve? 

The PR pingcap/tiup#867 introduces functions that will merge the workaround/description from errors.toml with the error message from the repository. Make sure there are no conflicts between code and error metafile, the PR pingcap/errors#31 remove workaround/description options.

### Check List 

Tests 

 - Unit test
 - Integration test

### Release Note

 - No release note

### CODE REVIEW

**Review by kennytm — COMMENTED** [review]
LGTM.

Please sign the CLA.

**Comment by lonng** [comment]
oops, seems to compile failure after merging master.

**Review by overvenus — APPROVED** [review]
LGTM

**Comment by lonng** [comment]
@overvenus Can the release-4.0 branch use the master branch of the parser?

**Comment by overvenus** [comment]
> @overvenus Can the release-4.0 branch use the master branch of the parser?

Not sure, we need to test. For now, BR keeps parser/kvproto the same as TiDB release-4.0

**Pull request merged**
