### PR TITLE
tests: make unblocksChecker get time synchronously (#792)

### LINKED ISSUE #778: Test pauseSuite.TestPause fails
1. What did you do?
If possible, provide a recipe for reproducing the error.

```
[2021-03-02T11:32:19.313Z] FAIL: pause_test.go:62: pauseSuite.TestPause
[2021-03-02T11:32:19.313Z] 
[2021-03-02T11:32:19.313Z] pause_test.go:99:
[2021-03-02T11:32:19.313Z]     c.Assert(&wg, unblocksBetween, 500*time.Millisecond, 520*time.Millisecond)
[2021-03-02T11:32:19.313Z] ... waitGroupPtr *sync.WaitGroup = &sync.WaitGroup{noCopy:sync.noCopy{}, state1:[3]uint32{0x0, 0x0, 0x0}}
[2021-03-02T11:32:19.313Z] ... min time.Duration = 500000000 ("500ms")
[2021-03-02T11:32:19.313Z] ... max time.Duration = 520000000 ("520ms")
[2021-03-02T11:32:19.313Z] ... WaitGroup did not unblock after maximum duration
```

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/5062/pipeline/69#step-360-log-118

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #792 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In br repo:
git pr https://github.com/pingcap/br/pull/794
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/br.git pr/794:release-4.0-71a83b19be7b
```

---

### What problem does this PR solve? 
Fixed #778.

### What is changed and how it works?
See [here](https://github.com/pingcap/br/issues/778#issuecomment-789585338).

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

<details>
<summary>With this script:</summary>

```bash
#!/bin/bash
i=0
success=0
while ((i<10)); do
if ! go test -count=1 github.com/pingcap/br/pkg/lightning/common 2>&1 >test_result.txt; then
        cp test_result.txt test_result_failed$i.txt
        ((i++))
else
        ((success++))
        if (( success % 50 == 1)); then
                echo -e "\rsuccess $success times..."
        fi
        if (( success > 1000000 )); then
                break
        fi
fi
done
```
</details>

Have succeed at least  18151 times... Without any failure.

### Release Note

 - No release note.

### CODE REVIEW

**Comment by YuJuncen** [comment]
`WaitGroup did not unblock after maximum duration, it was 589.424077ms`
Even 550ms isn't enough🤔?

/build

**Comment by overvenus** [comment]
LGTM

**Review by overvenus — APPROVED** [review]

**Pull request merged**
