### PR TITLE
update tidb version to fix CI

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

https://github.com/pingcap/tidb/pull/23529 change `@@tidb_enable_clustered_index` value from `ON/OFF` to `ON/OFF/INT_ONLY`

new added INT_ONLY can not pass check if using old tidb dep 

### What is changed and how it works?

update tidb version in go.mod

### Check List 

Tests 

 - No code

Code changes

 - n/a
 
Side effects

 - n/a
 
Related changes

 - Need to cherry-pick to the release branch 5.0

### Release Note

 - No release note

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/br/933)

### CODE REVIEW

**Comment by lysu** [comment]
need wait https://github.com/pingcap/tidb/pull/23529 be merged first

**Comment by lysu** [comment]
@3pointer @kennytm @overvenus  tidb's PR has merged, so we need merge this to avoid block BR's other PR

**Review by 3pointer — COMMENTED** [review]
/lgtm

**Review by kennytm — COMMENTED** [review]
/lgtm

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
