### PR TITLE
[cherry-pick] br: add region range check for batch scan regions(tidb#27192)

### PR DESCRIPTION
**Pull request by YuJuncen**
cherry-picking pingcap/tidb#27192

=== 

### What problem does this PR solve?
Currently, the implement of pd's batch scan regions can't guarantee consistency, so we add extra check for return returned region [startKey, endKey) check to ensure if there are potential range gap, the method will return an error.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [x] Unit test
- [x] Integration test

Side effects

Documentation

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by glorv — APPROVED** [review]

**Review by Leavrth — APPROVED** [review]

**Comment by YuJuncen** [comment]
/run-integration-test 
`file already exists` 🤔

**Comment by YuJuncen** [comment]
/run-integration-tests

It failed consistently? 🤔

**Comment by YuJuncen** [comment]
/run-integration-tests

something merged into master get things wrong?

**Pull request merged**
