### PR TITLE
task: expose table filter for `backup full` and `restore full`

### LINKED ISSUE #173: Support black-whist list
### Describe your feature request related problem:
Currently, BR only support three modes of backup:
* Full backup
* One DB backup
* One Table backup
And we may need support more general way of backup like black-white list on DBs or Tables, 
### Describe the feature you'd like:

1. Add config about black-white list, like DM [black-white list](https://pingcap.com/docs/stable/reference/tools/data-migration/configure/task-configuration-file/#task-configuration-file-template-basic)
2. use simple wildcard in command.
3. other ideas

### LINKED ISSUE #178: Support multiple databases / tables
### Describe your feature request related problem:

Support backing up multiple tables in a single command without needing the --backupts trick.

### Describe the feature you'd like:

A simplified version of #173. We support the following commands to backup/restore multiple databases or tables.

```sh
./br backup database --db firstdb --db seconddb 
#                                 ^~~~~~~~~~~~~
./br backup table --???? 'firstdb.firsttable' --???? '`second.db`.`2,tbl`'
```

Because the table name can contain a `.`, we need to support quoting by `` ` ``.

Unresolved question:

* Should we change the behavior of `database --db 'db1,db2'`? (currently backing up a single database named `` "db1,db2" ``
* Should we change the behavior of ``database --db '`db`'``? (currently backing up a single database named `` "`db`" ``
* What should the `--????` parameter be named?
* Should we keep the `table --db db1 --table tbl1` form?
* Do we want to support `table --???? 'db1.tbl1,db2.tbl2'`?
* Do we want to support `table --db db1 --???? tbl1 --???? tbl2`?
* Do we want to support `table --db db1 --db db2 --???? tbl1 --???? tbl2`?
* Should we support ANSI quotes `table --???? '"db1,db2"."tbl1,tbl2"'`?
* Should we reject if the inputs aren't proper identifiers `table --???? '!@#$.%^&*'`?

### Describe alternatives you've considered:

Don't support this and go straight to #173.

### Teachability, Documentation, Adoption, Migration Strategy:

If we decide to name `--????` as `--table` we'll need to rewrite all documentations.

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Fix #173, fix #178.

```sh
./br backup full -f 'db1.*' -f 'db2.tbl1' -f '!*.secrets' ...
```

### What is changed and how it works?

Use the new table-filter package in pingcap/tidb-tools#341.

### Check List 

Tests 

 - Integration test

Code changes

 - Has exported variable/fields change
    * `task.Config` has a new field `TableFilter`. The original two fields `CaseSensitive` and `Filter` are deprecated and should be removed after TiDB upgrades its BR dependency.

Side effects

Related changes

 - Need to cherry-pick to the release branch
    * should be included for 4.0.1.
 - Need to update the documentation
    * should document the new table filter format (a common page for all tools).

### Release Note

 - Supports advanced table filtering.

### CODE REVIEW

**Comment by overvenus** [comment]
Please also send a PR to update pingcap/docs, thanks!

**Comment by overvenus** [comment]
Please resolve the confliction.

**Comment by kennytm** [comment]
PTAL @3pointer

**Comment by 3pointer** [comment]
LGTM

**Pull request merged**
