### PR TITLE
ci: build on both Ubuntu and macOS

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve? 

Add CI job for building BR on both Ubuntu and macOS.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### Release note

- No release note

### CODE REVIEW

**Comment by kennytm** [comment]
Note that macOS jobs costs 10x the minutes of Linux (and Windows costs 2x).

**Comment by lance6716** [comment]
https://github.com/pingcap/dm/blob/c32de2423541bbe090deb3ab1fe51cd688a9f199/.github/workflows/check-and-build.yml#L33

a kindly reminder

**Comment by YuJuncen** [comment]
Could this be closed in favor of https://github.com/pingcap/br/pull/1051?

**Comment by kennytm** [comment]
#1051 only runs build while this also runs lint and unit test. If there's no plan to require unit tests passing outside of Linux (above "best effort" attempt), I support closing this.

(IMO running lint on multiple platforms is waste of time.)

**Comment by overvenus** [comment]
Closed in favor of #1051

**Pull request closed without merging**
