### PR TITLE
*: move lightning code into br (#512)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #512 to release-4.0

---

### What problem does this PR solve? 
Split #482 

### What is changed and how it works?
move lightning code into br.

### Check List 

Tests 

 - No code

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - No release not

### CODE REVIEW

**Comment by kennytm** [comment]
@3pointer CI build failed

**Comment by kennytm** [comment]
/run-integration-test

#540

**Review by overvenus — APPROVED** [review]
LGTM

**Pull request merged**
