### PR TITLE
adjust rawURL to local path if no u.Schema is given (#531)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #531 to release-4.0

---

### What problem does this PR solve? 
1. If we don't specify for `rawURL`, it will return an error. 
2. If we use a relative path for `rawURL`, it will return a wrong path.

### What is changed and how it works?
1. adjust rawURL to local path if no u.Schema is given
2. Use `filepath.Abs` to make sure path is transferred.

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - No release note

### CODE REVIEW

**Review by kennytm — COMMENTED** [review]
lgtm

**Comment by YuJuncen** [comment]
LGTM

**Comment by kennytm** [comment]
/run-integration-test

TiFlash.

**Comment by kennytm** [comment]
/run-integration-test 

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/3187/pipeline

```
[2020-09-27T09:56:28.389Z] CGO_ENABLED=0 tools/bin/golangci-lint run --enable-all --deadline 120s \
...
[2020-09-27T09:59:51.241Z] level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
```

**Review by kennytm — APPROVED** [review]

**Pull request merged**
