### PR TITLE
fill size in SSTMeta (#233)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #233 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In br repo:
git pr https://github.com/pingcap/br/pull/702
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/br.git pr/702:release-4.0-634701b9f73e
```

---

### What problem does this PR solve? 
Fix https://github.com/pingcap/br/issues/163

### What is changed and how it works?
fill size in sstmeta. but we need make sure this change work on tikv which has this 
 https://github.com/tikv/tikv/pull/7256, otherwise it will panic tikv.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch

### Release note

- Fix the issue that missing fileSize in SSTMeta might cause TiKV to generate a big region.

### CODE REVIEW

**Comment by overvenus** [comment]
Please add a version check, otherwise it may cause TiKV panic.

**Review by 3pointer — APPROVED** [review]
LGTM

**Comment by 3pointer** [comment]
> Please add a version check, otherwise it may cause TiKV panic.

we had this check [already](https://github.com/pingcap/br/pull/702#issuecomment-762189126), but forgot to pick #233 to release-4.0

**Comment by overvenus** [comment]
LGTM

Please also add a test in another PR.

**Pull request merged**
