### PR TITLE
cdclog: fix the lost ddl files

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve? 
Solve #870 

### What is changed and how it works?
ddl file use the first event's ts to build filename.
so the filter should be changed to `the first event's ts < endTS`

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Release Note

 - Fix the issue that cdclog lost some DDLs during restore.

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Comment by kennytm** [comment]
/run-integration-test 

```
[2021-06-16T08:15:58.454Z] TEST: [br_full_ddl] fail due to stats are not equal
```

**Review by glorv — APPROVED** [review]

**Comment by kennytm** [comment]
/run-integration-test 

```
[2021-07-05T03:14:55.223Z] TEST: [br_full_ddl] fail due to stats are not equal
```

**Comment by kennytm** [comment]
Still failing with the same error. I think the fix is wrong.

**Pull request merged**
