### PR TITLE
restore: fix restore summary log

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve? 
restore time cost is not accurate in summary log

### What is changed and how it works?
just collect total restore time cost, not accumulate all restore table time costs

### Check List 

Tests 
 - Manual test (add detailed scripts or steps below)

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by kennytm** [comment]
Does this work with `./br restore db` and `./br restore table`?

**Comment by kennytm** [comment]
/run-integration-test tidb=release-3.1 tikv=release-3.1 pd=release-3.1

**Comment by 3pointer** [comment]
> Does this work with `./br restore db` and `./br restore table`?

yes, restoreDBCommand and restoreTableCommand start with restoreAll function

**Comment by 3pointer** [comment]
/run-integration-test tidb=release-3.1 tikv=release-3.1 pd=release-3.1

**Comment by 3pointer** [comment]
/run-integration-test tidb=release-4.0 tikv=release-4.0 pd=release-4.0

**Pull request merged**
