### PR TITLE
Cherry-pick #367 and #358 to 3.1

### PR DESCRIPTION
**Pull request by YuJuncen**
NOTE: because #367 requires #358, so I cherry-picked them together.

#358  
---

### What problem does this PR solve? 
Fix https://github.com/pingcap/br/issues/328
Add a lock file at beginning, to make sure other backup task won't be able to start backup.

### What is changed and how it works?
Add a lock file when storage created.

### Check List 

Tests 

 - Integration test

### Release Note

 - Fix the issue that fast fail when multiple backup task start backup on same path.

---

#367 

---

### What problem does this PR solve? 
BR unit tests sometimes will fail because cannot start cluster(sometimes TiKV, sometimes TiFlash).

### What is changed and how it works?
- Change a new way to check whether TiFlash is started.
- Add a three times retry if fail to start test cluster.
- Change TiFlash config so it won't fail to synchronize.

### Check List 

Tests 

 - No code (Tests should be tested by what?)

### CODE REVIEW

**Comment by YuJuncen** [comment]
@3pointer PTAL(the #358 part)

**Comment by kennytm** [comment]
@3pointer CLA needs to be signed again for the bot 🥺

**Pull request merged**
