### PR TITLE
tests: outdated setting `--ratelimit` slow down CI time

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve? 

In branch release 4.0, in test `br_serv_outage`, args `limit-rate` is outdated.

### What is changed and how it works?

remove it.

### Release note

 -No release note

### CODE REVIEW

**Review by 3pointer — APPROVED** [review]

**Review by zwj-coder — APPROVED** [review]

**Comment by kennytm** [comment]
is there any way to bring back the "Update branch" button? doing it manually is annoying.

**Comment by kennytm** [comment]
```
[2021-07-08T04:42:40.025Z] pkg/task/common.go:289:15: undefined: utils
[2021-07-08T04:42:40.025Z] pkg/task/common.go:295:15: undefined: utils
```

the release branch is broken or something.

**Pull request merged**
