### PR TITLE
*: extracts runBackup/runRestore in cmd into pkg/task

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

To support BR via TiDB SQL (#154), we want an API which maps 1:1 to the CLI parameters. The packages in `pkg/` are too low-level to work with, while the high level driver (`runBackup`/`runRestore`) are hidden inside `cmd`, relying entirely on the `pflags` command line. This is not helpful to use BR as a library.

### What is changed and how it works?

1. Introduced the `pkg/task` package as the high-level entry point of the BR library. This package contains:
    * A `Config` structure to configure tasks.
    * Routines (`DefineXxxxFlags` and `ParseFromFlags`) which converts `pflags` into a `Config`
    * Driver functions like `RunBackup` and `RunRestore` extract out of `cmd/`. Users can simply fill out the configuration and use `RunBackup` to run the backup task.
2. Changed `cmd/` to use `pkg/task`.
3. The `Config` uses tidb-tool's [`filter`](https://pkg.go.dev/github.com/pingcap/tidb-tools@v3.0.9+incompatible/pkg/filter?tab=doc) package to cover for all of `full`/`db`/`table` cases. This also allows us to dump multiple tables with wildcard filtering.
4. Updated TiDB deps to 4.0.0-beta.

### Check List 

Tests 

 - Unit test

Code changes

* `--time-ago` now uses [Duration()](https://pkg.go.dev/github.com/spf13/pflag?tab=doc#FlagSet.Duration) and stored in the Config as a `time.Duration`. Thus, `(*backup.Client).GetTS()` takes a `time.Duration` instead of `string`. `--time-ago 0s` is now valid.
* `--pd` now uses [StringSlice()](https://pkg.go.dev/github.com/spf13/pflag?tab=doc#StringSlice), meaning `--pd 10.0.0.1:2379 --pd 10.0.0.2:2379,10.0.0.3:2379` is now valid and registers 3 PD addresses.
* **Backing up an empty cluster now causes error.**
* Even when restore failed, if any PD schedulers are removed, they will still be added back. We will also instruct the TiKVs to always switch back to normal mode.
* Some invisible internal changes:
    * `sendCredentials` is now passed as parameters instead of a global variable.
    * `GetDefaultMgr()` and the related global variables are removed. A new `*conn.Mgr` is constructed in every call of `RunBackup()`/`RunRestore()`. 

Side effects

 - Breaking backward compatibility

Related changes

### CODE REVIEW

**Comment by kennytm** [comment]
/run-integration-test tidb=release-3.1 tikv=release-3.1 pd=release-3.1

**Comment by kennytm** [comment]
/run-integration-test tidb=release-3.1 tikv=release-3.1 pd=release-3.1

**Comment by kennytm** [comment]
🤔 Not good. If the internal TiDB version is set to 4.0 (including the dependency at current master), it cannot load schema from the 3.1 cluster?

<details>

```
[2020-02-09T20:12:51.810Z] [2020/02/10 04:12:51.773 +08:00] [ERROR] [domain.go:1118] ["recover in domain failed"] [funcName=loadSchemaInLoop] [error="runtime error: invalid memory address or nil pointer dereference"] 

[buffer="goroutine 64 [running]:
github.com/pingcap/tidb/util.GetStack(...)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/util/misc.go:60
github.com/pingcap/tidb/domain.recoverInDomain(0x2ad13fe, 0x10, 0x1)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/domain/domain.go:1117 +0xb0
panic(0x27c7240, 0x41b5ef0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb/store/tikv/tikvrpc.(*Response).GetRegionError(0x0, 0xc0009c8d80, 0xc00085ddb0, 0xc0009fae60)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/tikvrpc/tikvrpc.go:676 +0x26
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReqCtx(0xc000a3cbb0, 0xc0009c8d80, 0xc0009fae60, 0x67, 0x2, 0xb, 0x4a817c800, 0xc000698000, 0xc0008b4040, 0x0, ...)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/region_request.go:156 +0x2ab
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReq(...)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/region_request.go:75
github.com/pingcap/tidb/store/tikv.(*tikvStore).SendReq(0xc00004e1e0, 0xc0009c8d80, 0xc0009fae60, 0x67, 0x2, 0xb, 0x4a817c800, 0x0, 0xc00032c930, 0x3f3c3ef2508c56dd)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/kv.go:383 +0xea
github.com/pingcap/tidb/store/tikv.(*LockResolver).getTxnStatus(0xc0000f9500, 0xc0009c8d80, 0x5c0ae5552ac0003, 0xc000bfa680, 0x12, 0x20, 0x5c0ae5552ac0007, 0x5c0ae5552ac0007, 0xbf8837d0edffe900, 0x6836fd87, ...)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/lock_resolver.go:470 +0x214
github.com/pingcap/tidb/store/tikv.(*LockResolver).getTxnStatusFromLock(0xc0000f9500, 0xc0009c8d80, 0xc000c5e5a0, 0x5c0ae5552ac0007, 0xc000c5e550, 0x1, 0x203000, 0xc000a3d001, 0xc000718eb0)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/lock_resolver.go:403 +0x11b
github.com/pingcap/tidb/store/tikv.(*LockResolver).ResolveLocks(0xc0000f9500, 0xc0009c8d80, 0x5c0ae5552ac0007, 0xc000a3d210, 0x1, 0x1, 0x5c0ae5552ac0003, 0xbbd, 0x3, 0xc0000594d0, ...)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/lock_resolver.go:295 +0x184
github.com/pingcap/tidb/store/tikv.(*clientHelper).ResolveLocks(0xc000a3d228, 0xc0009c8d80, 0x5c0ae5552ac0007, 0xc000a3d210, 0x1, 0x1, 0x4a817c800, 0x0, 0x0)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/coprocessor.go:792 +0x70
github.com/pingcap/tidb/store/tikv.(*tikvSnapshot).get(0xc000c5e320, 0xc0009c8d80, 0xc0000594a0, 0x24, 0x29, 0xc00042ec40, 0x2f26260, 0xc000bddb90, 0xc000a3d438, 0xf7d6bc)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/snapshot.go:351 +0x46d
github.com/pingcap/tidb/store/tikv.(*tikvSnapshot).Get(0xc000c5e320, 0x2f261e0, 0xc0000540d0, 0xc0000594a0, 0x24, 0x29, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/snapshot.go:282 +0x1c1
github.com/pingcap/tidb/structure.(*TxStructure).Get(0xc0007ac280, 0x4216dd0, 0x10, 0x10, 0xc000a3d5a0, 0xf43788, 0x30, 0x28c62e0, 0xc000c5e301)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/structure/string.go:36 +0xb6
github.com/pingcap/tidb/structure.(*TxStructure).GetInt64(0xc0007ac280, 0x4216dd0, 0x10, 0x10, 0xc000c5e320, 0x0, 0xbf8837d0edff8af9)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/structure/string.go:45 +0x4d
github.com/pingcap/tidb/meta.(*Meta).GetSchemaVersion(...)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/meta/meta.go:186
github.com/pingcap/tidb/domain.(*Domain).loadInfoSchema(0xc00033fb00, 0xc00021d0e0, 0x2a, 0x5c0ae5552ac0007, 0x0, 0x0, 0x0, 0x0, 0xf78e00, 0x0, ...)
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/domain/domain.go:91 +0x1ff
github.com/pingcap/tidb/domain.(*D"] 

[stack="github.com/pingcap/tidb/domain.recoverInDomain
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/domain/domain.go:1118
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:679
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:199
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:394
github.com/pingcap/tidb/store/tikv/tikvrpc.(*Response).GetRegionError
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/tikvrpc/tikvrpc.go:676
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReqCtx
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/region_request.go:156
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReq
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/region_request.go:75
github.com/pingcap/tidb/store/tikv.(*tikvStore).SendReq
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/kv.go:383
github.com/pingcap/tidb/store/tikv.(*LockResolver).getTxnStatus
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/lock_resolver.go:470
github.com/pingcap/tidb/store/tikv.(*LockResolver).getTxnStatusFromLock
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/lock_resolver.go:403
github.com/pingcap/tidb/store/tikv.(*LockResolver).ResolveLocks
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/lock_resolver.go:295
github.com/pingcap/tidb/store/tikv.(*clientHelper).ResolveLocks
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/coprocessor.go:792
github.com/pingcap/tidb/store/tikv.(*tikvSnapshot).get
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/snapshot.go:351
github.com/pingcap/tidb/store/tikv.(*tikvSnapshot).Get
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/snapshot.go:282
github.com/pingcap/tidb/structure.(*TxStructure).Get
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/structure/string.go:36
github.com/pingcap/tidb/structure.(*TxStructure).GetInt64
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/structure/string.go:45
github.com/pingcap/tidb/meta.(*Meta).GetSchemaVersion
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/meta/meta.go:186
github.com/pingcap/tidb/domain.(*Domain).loadInfoSchema
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/domain/domain.go:91
github.com/pingcap/tidb/domain.(*Domain).Reload
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/domain/domain.go:359
github.com/pingcap/tidb/domain.(*Domain).loadSchemaInLoop
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/domain/domain.go:476"]
```

</details>

**Comment by kennytm** [comment]
/run-integration-test tidb=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by 3pointer** [comment]
It seems `Raw kv` backup & resctore can be separate easily after task introduced. lets merge this PR first. cc @overvenus

**Pull request merged**
