### PR TITLE
pkg/*:adjust according the new version of github.com/pingcap/tidb/kv

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: shirly <AndreMouche@126.com>

### What problem does this PR solve? 

This PR adjust the serval implementation  of functions for interfaces from github.com/pingcap/tidb/kv adjust the new version of `tidb/kv` package

### Check List 

 - Unit test

### Release Note

- No release note

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Comment by kennytm** [comment]
(https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/br_ghpr_unit_and_integration_test/runs/7707/nodes/64/log/?start=0 spurious error)

```
[2021-03-29T03:45:51.467Z] FAIL: client_test.go:48: testRestoreClientSuite.TestCreateTables
[2021-03-29T03:45:51.467Z] 
[2021-03-29T03:45:51.467Z] client_test.go:49:
[2021-03-29T03:45:51.467Z]     c.Assert(s.mock.Start(), IsNil)
[2021-03-29T03:45:51.467Z] ... value *errors.withStack = listen tcp 0.0.0.0:10266: bind: address already in use ("listen tcp 0.0.0.0:10266: bind: address already in use")
```

**Pull request merged**
