### PR TITLE
lightning: refactor the `backend` package (#877)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #877 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In br repo:
git pr https://github.com/pingcap/br/pull/902
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/br.git pr/902:release-5.0-2652f252f175
```

---

### What problem does this PR solve? 

Split the `pkg/lightning/backend` package into multiple parts, intended to be the true fix for #837 surviving `go mod tidy`.

### What is changed and how it works?

The `backend` package itself now only contains the abstract type `Backend`. The concrete stuff are now split into multiple subpackages:

* Local backend into `pkg/lightning/backend/local`
* TiDB backend into `pkg/lightning/backend/tidb`
* Importer backend into `pkg/lightning/backend/importer`
* KV encoder stuff into `pkg/lightning/backend/kv`, **intended to be merged into `pkg/kv` in some future PR**
* TiKV connection stuff into `pkg/lightning/tikv`
* The version checking code is split into `pkg/lightning/backend/importer`, pkg/lightning/backend/local`, `pkg/lightning/tikv` and `pkg/version` depending on the component being checked.

Reverted #838 as it is proved to be useless.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - No release note

### CODE REVIEW

**Comment by lysu** [comment]
hi @kennytm please help merge this PR, tidb will introduce dirty dependencies without this PR in release-5.0

**Review by kennytm — APPROVED** [review]

**Pull request merged**
