### PR TITLE
cmd,task: disable stray command line args, and log the command in LogArguments

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

1. It was confusing that `--checksum false` does not actually disable checksum, because `--checksum` as a boolean flag already means `--checksum=true`. So `--checksum false` becomes `--checksum=true false`, and that extra `false` becomes a stray argument, which is ignored before this PR.

2. `LogArguments` did not record whether it is a "backup" or "restore" making it a bit hard to determine the data direction when reading logs.

### What is changed and how it works?

1. Added `Args: cobra.NoArgs` to all leaf commands so using `--checksum false` will result in

    ```
    Error: unknown command "false" for "br backup full"
    ```

    rather than silently keeping checksum.

2. Record the command being executed inside `LogArguments`.

    Note that I changed `LogArguments` from using `VisitAll` to `Visit`. Originally in #55 it was using `VisitAll` to print all args, however it was changed in #292 to condition on `f.Changed`, so perhaps let's just use `Visit` directly 🙃.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
    * Run and check the log.

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - BR no longer accepts `--checksum false` in command line, which did not disable checksum. The correct usage always include the `=` sign: `--checksum=false`.

### CODE REVIEW

**Review by overvenus — APPROVED** [review]
LGTM

**Comment by overvenus** [comment]
Please update your PR title.https://github.com/pingcap/community/blob/01457b0bba90b92a6d8f6c715a3b18cc432c6a12/contributors/commit-message-pr-style.md

**Comment by overvenus** [comment]
/run-integration-tests

Tests fail due to recent change in TiKV which has been fixed by https://github.com/tikv/tikv/pull/8971

**Comment by kennytm** [comment]
/run-integration-test

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/3629/pipeline/77 (unit test) 🤔 

```
[2020-11-06T06:34:26.479Z] CGO_ENABLED=0 tools/bin/golangci-lint run --enable-all --deadline 120s \
...
[2020-11-06T06:36:11.482Z] make[1]: *** [static] Killed
```

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/3629/pipeline/112 (br_tiflash)

```
[2020-11-06T06:39:28.878Z] failed to restore, before: 1000; after: 960
```

**Pull request merged**
