### PR TITLE
filter out all TiFlash nodes when retrieving lists of stores from PD

### LINKED ISSUE #180: BR should filter out TiFlash nodes
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Backup from a cluster where some TiFlash nodes are running

2. What did you expect to see?

Success.

3. What did you see instead?

Backup failed with "Unimplemented" error in `SendBackup()`, on this line:

https://github.com/pingcap/br/blob/328ad699d00ff23f1938b4c3dff3f3e4ecc5226c/pkg/backup/client.go#L684

Since TiFlash cannot participate in BR anyway, we should just filter these nodes out.

4. What version of BR and TiDB/TiKV/PD are you using?

3.1.0-beta.1

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Fix #180.

### What is changed and how it works?

On backup, if a store has label `engine=tiflash`, skip it.

On restore, if a TiFlash store exists, return error.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by kennytm** [comment]
cc @jebter

**Comment by 5kbpers** [comment]
Will tiflash crash because of the `ingest` cmd with nonexistent sst?

**Comment by kennytm** [comment]
not sure, i can't find a tiflash binary to test and the repo is 404. cc @nolouch ?

**Comment by kennytm** [comment]
Seems there are still two places where TiFlash can leak in 🤦‍:

1. Scattering can pick TiFlash (needs to change PD)
2. TiFlash may learn the "Ingest" Raft command (meaning TiFlash have to implement sst_importer anyway, plus it needs a copy of that SST file being ingested)

**Comment by kennytm** [comment]
PTAL @overvenus, now errors on restore (and skip on backup).

**Comment by GregoryIan** [comment]
@overvenus PTAL

**Pull request merged**
