### PR TITLE
summary: log failure message to terminal

### LINKED ISSUE #1016: When backing up an empty cluster, nothing will be output.
Please answer these questions before submitting your issue. Thanks!!
1. What did you do?
When backing up an empty cluster, nothing will be output.It will not show that the backup is complete, nor will it show an error.

2. What did you expect to see?
Similar to a summary ：["Full backup Failed summary: total backup ranges: 0, total success: 0, total failed: 0"] [BackupTS=xxxxxxxxxxxxxxxxxx]

3. What did you see instead?
Nothing at all

4. What version of BR and TiDB/TiKV/PD are you using?

5. Operation logs
command：
command

brlog：
log

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve? 
Fixed #1016.

### What is changed and how it works?
```diff
diff --git a/pkg/summary/collector.go b/pkg/summary/collector.go
index 84dabaeb..3e3264d1 100644
--- a/pkg/summary/collector.go
+++ b/pkg/summary/collector.go
@@ -188,7 +188,7 @@ func (tc *logCollector) Summary(name string) {
                for unitName, reason := range tc.failureReasons {
                        logFields = append(logFields, zap.String("unit-name", unitName), zap.Error(reason))
                }
-               log.Info(name+" failed summary", logFields...)
+               tc.log(name+" failed summary", logFields...)
                return
        }
```

`tc.Log` would tee events to terminal.

**BTW: should be replace this with things like `logutil.InfoTerm`, which would be more generic?**

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
image

### Release Note

 - Fix a bug that caused, when backup failed, nothing would be printed to terminal.

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by overvenus** [comment]
Could you also log the error to the log file?

**Comment by YuJuncen** [comment]
@overvenus `tc.log` did that. 

https://github.com/pingcap/br/blob/d2fdd23c47b3f88cb26a4d646e5bdfb6d148cfbd/pkg/summary/collector.go#L54-L67

**Comment by YuJuncen** [comment]
Seems the `tikv.backoffer` didn't back off as intended (20s), and exceeded the retry time limit too early...

/run-integration-tests

**Pull request merged**
