### PR TITLE
Makefile: fix version number on macOS

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve? 

Fix make on macOS by correct regex.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

```
git tag v5.0.2
git checkout -b refs/tags/v5.0.2
make build
```

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - No release note.

### CODE REVIEW

**Comment by overvenus** [comment]
@zhouqiang-cl PTAL

**Comment by zhouqiang-cl** [comment]
It works!!!

**Comment by zhouqiang-cl** [comment]
LGTM

**Pull request merged**
