### PR TITLE
Cherry-pick:  row data lost (#315)

### PR DESCRIPTION
**Pull request by 3pointer**
cherry-pick #315 to release-3.1

### What problem does this PR solve? 
Try fix row data lost.

### What is changed and how it works?
row id bigger than 9151314442816847872 after encoded may exceed than default max range end [`0xff`]( https://github.com/pingcap/br/blob/943e502cc14da6bff81d15b78d2468500526a44b/pkg/restore/util.go#L106), change it `10*[0xff]`
### Check List 

Tests 

 - Integration test
 - manual test

### Release Note

 - Fix the row data lost when row_id bigger than 9151314442816847872

### CODE REVIEW

**Comment by kennytm** [comment]
```
[2020-05-28T09:39:45.357Z] [2020/05/28 17:39:45.238 +08:00] [ERROR] [backup.go:139] ["LastBackupTS is larger than current TS"] [stack="github.com/pingcap/log.Error\n\t/go/pkg/mod/github.com/pingcap/log@v0.0.0-20200117041106-d28c14d3b1cd/global.go:42\ngithub.com/pingcap/br/pkg/task.RunBackup\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/pkg/task/backup.go:139\ngithub.com/pingcap/br/cmd.runBackupCommand\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/cmd/backup.go:22\ngithub.com/pingcap/br/cmd.newTableBackupCommand.func1\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/cmd/backup.go:99\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\ngithub.com/pingcap/br.main\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/main.go:54\ngithub.com/pingcap/br.TestRunMain.func1\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/main_test.go:39"]

[2020-05-28T09:39:45.357Z] [2020/05/28 17:39:45.238 +08:00] [INFO] [ddl.go:568] ["[ddl] DDL closed"] [ID=dadc58b0-44b5-4d50-8997-f25aa6f830bd] ["take time"=449.82µs]

[2020-05-28T09:39:45.357Z] [2020/05/28 17:39:45.238 +08:00] [INFO] [ddl.go:464] ["[ddl] stop DDL"] [ID=dadc58b0-44b5-4d50-8997-f25aa6f830bd]

[2020-05-28T09:39:45.357Z] [2020/05/28 17:39:45.239 +08:00] [INFO] [domain.go:566] ["domain closed"] ["take time"=948.114µs]

[2020-05-28T09:39:45.357Z] [2020/05/28 17:39:45.239 +08:00] [INFO] [collector.go:172] ["Table backup Failed summary : total backup ranges: 0, total success: 0, total failed: 0"]

[2020-05-28T09:39:45.357Z] Error: LastBackupTS is larger than current TS
```

Maybe spurious

**Comment by 3pointer** [comment]
> https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/1729/pipeline
> 
> ```
> [2020-05-28T09:39:45.357Z] [2020/05/28 17:39:45.238 +08:00] [ERROR] [backup.go:139] ["LastBackupTS is larger than current TS"] [stack="github.com/pingcap/log.Error\n\t/go/pkg/mod/github.com/pingcap/log@v0.0.0-20200117041106-d28c14d3b1cd/global.go:42\ngithub.com/pingcap/br/pkg/task.RunBackup\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/pkg/task/backup.go:139\ngithub.com/pingcap/br/cmd.runBackupCommand\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/cmd/backup.go:22\ngithub.com/pingcap/br/cmd.newTableBackupCommand.func1\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/cmd/backup.go:99\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\ngithub.com/pingcap/br.main\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/main.go:54\ngithub.com/pingcap/br.TestRunMain.func1\n\t/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/src/github.com/pingcap/br/main_test.go:39"]
> 
> [2020-05-28T09:39:45.357Z] [2020/05/28 17:39:45.238 +08:00] [INFO] [ddl.go:568] ["[ddl] DDL closed"] [ID=dadc58b0-44b5-4d50-8997-f25aa6f830bd] ["take time"=449.82µs]
> 
> [2020-05-28T09:39:45.357Z] [2020/05/28 17:39:45.238 +08:00] [INFO] [ddl.go:464] ["[ddl] stop DDL"] [ID=dadc58b0-44b5-4d50-8997-f25aa6f830bd]
> 
> [2020-05-28T09:39:45.357Z] [2020/05/28 17:39:45.239 +08:00] [INFO] [domain.go:566] ["domain closed"] ["take time"=948.114µs]
> 
> [2020-05-28T09:39:45.357Z] [2020/05/28 17:39:45.239 +08:00] [INFO] [collector.go:172] ["Table backup Failed summary : total backup ranges: 0, total success: 0, total failed: 0"]
> 
> [2020-05-28T09:39:45.357Z] Error: LastBackupTS is larger than current TS
> ```
> 
> Maybe spurious

This test is expect to fail

**Pull request merged**
