### PR TITLE
cherry-pick #300 to v4.0

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve? 

#300 fixes the incompatibility of new PD client, but not yet cherry-picked to v4.0.

This blocks updating TiDB requirement.

### What is changed and how it works?

Cherry pick #300 to 4.0

### Check List 

Tests 

 - No code (Yes, I just update go.mod, farther tests are in original PR.)

### Release Note

 - No release note

### CODE REVIEW

**Comment by 3pointer** [comment]
LGTM

**Comment by YuJuncen** [comment]
/run-integration-test

`[2020-06-08T03:45:30.616Z] failed to start tiflash`

**Comment by YuJuncen** [comment]
/run-integration-test

`Recursively delete the current directory from the workspace` what the...🙃

**Comment by YuJuncen** [comment]
/run-integration-test

Maybe... Parallel running test cases is too mean for CI...?

`[2020-06-08T03:58:24.604Z] Failed to initialize TiKV cluster`

**Comment by YuJuncen** [comment]
/run-integration-test

#324 ?

```
[2020-06-08T04:19:49.419Z] [2020/06/08 12:19:48.519 +08:00] [WARN] [retry_interceptor.go:61] ["retrying of unary invoker failed"] [target=endpoint://client-00fee13d-462b-4dbd-a97b-d5aa9ce2f085/127.0.0.1:2379] [attempt=0] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"]
```

**Pull request merged**
