### PR TITLE
log: optimize some log (#515)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #515 to release-4.0

---

### What problem does this PR solve? 
to optimize log info.

### What is changed and how it works?
1. change log.Fatal to log.Panic, because we need the `defer` work, e.g. to set config back.
2. log more information on error level log. e.g. give store id on backup response log.

### Check List 

Tests 

 - No code

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - No release note.

### CODE REVIEW

**Review by kennytm — COMMENTED** [review]
lgtm

**Comment by YuJuncen** [comment]
LGTM

**Comment by kennytm** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/3033/pipeline

**Review by IANTHEREAL — APPROVED** [review]

**Pull request merged**
