### PR TITLE
test: fix br_table_partition integration test

### PR DESCRIPTION
**Pull request by 3pointer**
cherry-pick #667 to release-5.0

---

### What problem does this PR solve? 
Fix br_table_parition test failed

### What is changed and how it works?
upgrade tidb dependency && enable partition feature

### Check List 

Tests 

 - Integration test

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - No release note

### CODE REVIEW

**Comment by 3pointer** [comment]
/run-all-tests tikv=release-5.0-rc tidb=release-5.0-rc pd=release-5.0-rc

**Comment by 3pointer** [comment]
/run-all-tests tikv=release-5.0-rc tidb=release-5.0-rc pd=release-5.0-rc

**Review by kennytm — COMMENTED** [review]
LGTM

**Pull request merged**
