### PR TITLE
makefile: fix the problem that `make` stuck in macOS (#938)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #938 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In br repo:
git pr https://github.com/pingcap/br/pull/941
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/br.git pr/941:release-5.0-403d1e1584fa
```

---

### What problem does this PR solve? 
In macOS, `make` would stick at checking backuppb, with a warning 'recursive search from stdin.'

### What is changed and how it works?
When `-R` provided but no file provided, `grep` of macOS will wait for read from stdin, omit the `-R` flag. This PR make the make script provide the search target explicitly.

But `grep` of linux would implicit use current directory to search, so this bug won't appear in linux.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

### Release Note

 - No release note

### CODE REVIEW

**Comment by YuJuncen** [comment]
`Confirm that you know what this command will do and use it at your own risk [Y/N]` 🤔

/run-integration-tests

**Comment by kennytm** [comment]
CI is green.

**Pull request merged**
