### PR TITLE
go.mod: update TiDB

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve? 
Update TiDB version.

### What is changed and how it works?
`GOPROXY=direct go get -u github.com/pingcap/tidb@master`

### Release Note

 - No release note.

### CODE REVIEW

**Comment by lance6716** [comment]
does this PR solve a specific problem?

**Comment by kennytm** [comment]
we just regularly update the dependencies right?

/lgtm

**Comment by overvenus** [comment]
Closed by  #1035

**Pull request closed without merging**
