### PR TITLE
restore: Make all download error as retryable

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Workaround tikv/tikv#7846 and the "Restore" part of tidb-challenge-program/bug-hunting-issue#72.

### What is changed and how it works?

Allow ErrDownloadFailed to be retried. The transient 5xx errors from the cloud server should be retryable.

This is currently too relaxed, as truly unrecoverable errors such as file-not-found will also get retried. But the worst case is retrying this for 8 times, so this seems to be an acceptable compromise. 

We could tighten it back when we have more precise error handling from TiKV.

In the future we may tighten it back on truly recoverable errors such as file-not-found. but the worst of having a false negative is just hitting the same error 8 times. 

Additionally, changed `WithRetry` to return a `multierr` so no errors are lost.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
    * Cherry-pick to 3.1.

### Release Note

 - Improved robustness of restore, reducing chance of failure due to transient network error with cloud storage.

### CODE REVIEW

**Comment by shuijing198799** [comment]
maybe backup also need to retry on upload

**Comment by kennytm** [comment]
(Accidentally verified on DBaaS that this works, after receiving a DNS error.)

```
tikv-0.log:[2020/05/20 06:06:08.328 +00:00] [ERROR] [sst_importer.rs:129] ["download failed"] [err="Cannot read gcs://<REDACTED>//66_23424_314_57ed0c06e1488d74165852a6acc6309e4985479d550bb9c2059756b6216e1b24_write.sst: request GCS access token failed: error sending request for url (https://oauth2.googleapis.com/token): error trying to connect: dns error: Device or resource busy (os error 16)"] [name=66_23424_314_57ed0c06e1488d74165852a6acc6309e4985479d550bb9c2059756b6216e1b24_write.sst] [meta="uuid: A25481D8C349472BACF2D3E4FD148F78 range { start: 7480000000000000FF5C5F72800000000CFF2C30ED0000000000FA end: 7480000000000000FF5C5F72800000000DFF8737F60000000000FA } length: 1703709 cf_name: \"write\" region_id: 23460 region_epoch { conf_ver: 5 version: 335 }"]
tikv-0.log:[2020/05/20 06:06:26.655 +00:00] [INFO] [sst_importer.rs:125] [download] [range="Some(start: 7480000000000000FF5C5F72800000000CFF2C30ED0000000000FAFFFFFFFFA1BC1AB4 end: 7480000000000000FF5C5F72800000000DFF8737F50000000000FAFFFFFFFFA1BC1AB4)"] [name=66_23424_314_57ed0c06e1488d74165852a6acc6309e4985479d550bb9c2059756b6216e1b24_write.sst] [meta="uuid: 8318DF5367634F43898F8CD36F0C52AC range { start: 7480000000000000FF5C5F72800000000CFF2C30ED0000000000FA end: 7480000000000000FF5C5F72800000000DFF8737F60000000000FA } length: 1703709 cf_name: \"write\" region_id: 23460 region_epoch { conf_ver: 5 version: 335 }"]
tikv-1.log:[2020/05/20 06:06:27.385 +00:00] [INFO] [sst_importer.rs:125] [download] [range="Some(start: 7480000000000000FF5C5F72800000000CFF2C30ED0000000000FAFFFFFFFFA1BC1AB4 end: 7480000000000000FF5C5F72800000000DFF8737F50000000000FAFFFFFFFFA1BC1AB4)"] [name=66_23424_314_57ed0c06e1488d74165852a6acc6309e4985479d550bb9c2059756b6216e1b24_write.sst] [meta="uuid: 8318DF5367634F43898F8CD36F0C52AC range { start: 7480000000000000FF5C5F72800000000CFF2C30ED0000000000FA end: 7480000000000000FF5C5F72800000000DFF8737F60000000000FA } length: 1703709 cf_name: \"write\" region_id: 23460 region_epoch { conf_ver: 5 version: 335 }"]
tikv-2.log:[2020/05/20 06:06:28.089 +00:00] [INFO] [sst_importer.rs:125] [download] [range="Some(start: 7480000000000000FF5C5F72800000000CFF2C30ED0000000000FAFFFFFFFFA1BC1AB4 end: 7480000000000000FF5C5F72800000000DFF8737F50000000000FAFFFFFFFFA1BC1AB4)"] [name=66_23424_314_57ed0c06e1488d74165852a6acc6309e4985479d550bb9c2059756b6216e1b24_write.sst] [meta="uuid: 8318DF5367634F43898F8CD36F0C52AC range { start: 7480000000000000FF5C5F72800000000CFF2C30ED0000000000FA end: 7480000000000000FF5C5F72800000000DFF8737F60000000000FA } length: 1703709 cf_name: \"write\" region_id: 23460 region_epoch { conf_ver: 5 version: 335 }"]
```

**Comment by shuijing198799** [comment]
Repeated testing using the 1.4 T data set did not reproduce
```
I0520 04:32:05.724178       1 restore.go:86] [2020/05/20 04:32:05.724 +00:00] [INFO] [collector.go:195] ["Full restore Success summary: total restore files: 35252, total success: 35252, total failed: 0, total take(s): 6115.33, total kv: 10140081556, total size(MB): 1478230.72, avg speed(MB/s): 241.73"] ["split region"=1m46.683811285s] ["restore checksum"=11m11.709348139s] ["restore ranges"=19861]
```
and catch tikv log 
```
[2020/05/20 06:06:08.328 +00:00] [ERROR] [sst_importer.rs:129] ["download failed"] [err="Cannot read gcs://dbaas-hibernatetest1T//66_23424_314_57ed0c06e1488d74165852a6acc6309e4985479d550bb9c2059756b6216e1b24_write.sst: request GCS access token failed: error sending request for url (https://oauth2.googleapis.com/token): error trying to connect: dns error: Device or resource busy (os error 16)"] [name=66_23424_314_57ed0c06e1488d74165852a6acc6309e4985479d550bb9c2059756b6216e1b24_write.sst] [meta="uuid: A25481D8C349472BACF2D3E4FD148F78 range { start: 7480000000000000FF5C5F72800000000CFF2C30ED0000000000FA end: 7480000000000000FF5C5F72800000000DFF8737F60000000000FA } length: 1703709 cf_name: \"write\" region_id: 23460 region_epoch { conf_ver: 5 version: 335 }"]
```
It seems fix the issue https://github.com/tikv/tikv/issues/7846 . thx @kennytm

**Comment by shuijing198799** [comment]
fix  tikv/tikv#7846

**Comment by shuijing198799** [comment]
fix https://github.com/tikv/tikv/issues/7846

**Comment by shuijing198799** [comment]
fix https://github.com/tikv/tikv/issues/7846

**Pull request merged**
