### PR TITLE
*: update tidb

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve? 
update tidb dependency

### What is changed and how it works?
- go get -u tidb
- update mockChecksumKVClient to meet new interface
- use kv.PriorityLow instead of tikvstore.PriorityLow

### Check List 

Tests 
 - Unit test

### Release note
- No release note

### CODE REVIEW

**Comment by tisonkun** [comment]
@disksing iiuc `Release Note` should be `Release note` because it checks exactly matched.

**Comment by disksing** [comment]
> @disksing iiuc `Release Note` should be `Release note` because it checks exactly matched.

Interesting. `Release Note` It's from the PR template.

**Pull request merged**
