### PR TITLE
Spelling error in code comment

### PR DESCRIPTION
**Pull request by tongtongyin**
### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Release Note

 -

### CODE REVIEW

**Review by 3pointer — COMMENTED** [review]
LGTM, thanks~

**Comment by kennytm** [comment]
Hi @tongtongyin you need to sign the CLA for us to merge this PR. As described in https://github.com/pingcap/br/pull/569#issuecomment-716485415 above, you either need to [add](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/adding-an-email-address-to-your-github-account) the email address `lvtuyintongtong<at>gmail.com` to your GitHub account, or amend all 3 commits' author with the primary GitHub email address (`37565148+tongtongyin@users.noreply.github.com`).

**Comment by tongtongyin** [comment]
I have signed License, But it shows no sign, I guess something went wrong elsewhere.

**Review by overvenus — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
