### PR TITLE
backup: optimize progress update logic (#1047)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1047 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In br repo:
git pr https://github.com/pingcap/br/pull/1054
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/br.git pr/1054:release-5.0-6d3e3c9a1540
```

---

### What problem does this PR solve? 
Solve https://github.com/pingcap/br/issues/1042

### What is changed and how it works?
if backup ranges is more than 100, we can use range as the unit of progress.

### Check List 

Tests 
 - Manual test (add detailed scripts or steps below)

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Release Note

 - Fix the issue that backup costs too much time to count progress units when backup lots of ranges.

### CODE REVIEW

**Comment by kennytm** [comment]
```
java.io.IOException: Cannot read more than 2Gib at a time

	at org.jenkinsci.plugins.workflow.log.FileLogStorage.stepLog(FileLogStorage.java:290)

	at org.jenkinsci.plugins.workflow.support.actions.LogStorageAction.getLogText(LogStorageAction.java:62)

	at io.jenkins.blueocean.rest.impl.pipeline.PipelineStepImpl.getLog(PipelineStepImpl.java:144)

	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)

	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)

	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)

	at org.kohsuke.stapler.MetaClass$2.doDispatch(MetaClass.java:219)
```

🤔

**Review by lichunzhu — COMMENTED** [review]
/lgtm

**Pull request merged**
